---
version:  "3.8"
services:
  mydb:
    image: postgres
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_password
      POSTGRES_USER_FILE: /run/secrets/pg_user
      POSTGRES_DB_FILE: /run/secrets/pg_db
    secrets:
      - pg_password
      - pg_user
      - pg_db
    deploy:
      replicas: 2

  adminer:
    image: adminer
    ports:
      - 7070:8080
    deploy:
      replicas:2
secrets:
  pg_password:
    external: true
  pg_user:
    external: true
  pg_db:
    external: true

...