---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    type: proxy
spec:
  containers:
    - name: mynginx
      image: nginx
      resources:
        requests:
          memory: "128Mi"
          cpu: "250Mi"
        limits:
          memory: "256Mi"
          cpu: "200Mi"

...
