---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    type: database
    author: mercy
spec:
  containers:
    - name: mypostgres
      image: postgres
      env:
        - name: POSTGRES_USER
          value: minus
        - name: POSTGRES_PASSWORD
          value: zion
        - name: POSTGRES_NAME
          value: mypgres
...
