---
- name: Error Handling or Exception Handling
  host: all
  task:
    - block:
        - name: Install git using apt module
          apt:
            name: git
            state: present
            update_cache: yes
      rescue:
        - name: Install git using yum module
          yum:
            name: git
            state: present
            update_cache: yes
      always:
        - name: Display success msg
          debug:
            msg: "Git installation successful"


...